spring:
  config:
    import:
      - 'optional:file:./env.properties'
  datasource:
    url: "jdbc:postgresql://streamit-streamit.l.aivencloud.com:28578/defaultdb?sslmode=require"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000